task:
  name: FreeBSD 12 amd64 stable
  freebsd_instance:
    image: freebsd-12-1-release-amd64
    cpu: 1
    memory: 1
  env:
    RUST_BACKTRACE: 1
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - . $HOME/.cargo/env
    - cargo build
    - cargo build --all-features
  test_script:
    - . $HOME/.cargo/env
    - cargo test --no-fail-fast --all-features
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: Linux amd64 1.36
  container:
    image: rust:1.36
    cpu: 1
    memory: 1
  env:
    RUST_BACKTRACE: 1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - cargo build
    - cargo build --all-features
  test_script:
    - ip addr
    - cat /etc/hosts || true
    - ip addr add ::1 dev lo scope host
    - cargo test --no-fail-fast --all-features
    - cargo run --example limits
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: Linux amd64 nightly
  container:
    image: rustlang/rust:nightly
    cpu: 1
    memory: 1
  env:
    RUST_BACKTRACE: 1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - cargo build -Z minimal-versions
    - cargo build -Z minimal-versions --features mio_06
    - cargo build -Z minimal-versions --features mio_07
    - cargo build -Z minimal-versions --all-features
  test_script:
    - rm Cargo.lock
    - cargo test -Z minimal-versions --no-fail-fast
    - cargo test -Z minimal-versions --no-fail-fast --all-features
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: Linux i686 stable
  container:
    image: rust:latest
    cpu: 1
    memory: 1
  env:
    RUST_BACKTRACE: 1
  setup_script:
    - apt-get update
    - apt-get install -yqq gcc gcc-multilib linux-libc-dev
    - rustup target add i686-unknown-linux-gnu
    - rustup target add i686-unknown-linux-musl
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - cargo build --target i686-unknown-linux-gnu --all-features
    - cargo build --target i686-unknown-linux-musl --all-features
  test_script:
    - cargo test --target i686-unknown-linux-gnu --no-fail-fast --all-features
    - cargo test --target i686-unknown-linux-musl --no-fail-fast --all-features
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: Cross-check stable
  container:
    image: rust:latest
    cpu: 1
    memory: 1
  setup_script:
    - rustup component add clippy
    - rustup target add aarch64-linux-android
    - rustup target add x86_64-unknown-linux-gnux32
    - rustup target add powerpc-unknown-linux-gnu
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - cargo clippy --all-features
    - cargo check --target aarch64-linux-android --tests --examples --all-features
    - cargo check --target x86_64-unknown-linux-gnux32 --tests --examples --all-features
    - cargo check --target powerpc-unknown-linux-gnu --tests --examples --all-features
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
